### PR TITLE
CMOS-156: Update add cluster form for CB7 and make Prometheus/CBMM optional

### PR DESCRIPTION
**Pull request by markspolakovs**

### CODE REVIEW

**Review by patrick-stephens — APPROVED** [review]
I assume it works? Be good to have a screenshot or similar for any similar changes in the future.

**Comment by markspolakovs** [comment]
Good point - yeah, tested it, though this is slightly difficult to screenshot:

image

**Comment by patrick-stephens** [comment]
> Good point - yeah, tested it, though this is slightly difficult to screenshot:
> 
> image

What are the defaults? Both ticked?

**Comment by markspolakovs** [comment]
Yep, default is both enabled, and the buttons are only disabled if neither is.

**Pull request merged**
