### PR TITLE
Add dashboards from Show & Tell demo

### PR DESCRIPTION
**Pull request by markspolakovs**
These will likely change considerably before being shipped to customers, this is just as a starting point.

### CODE REVIEW

**Comment by redm2** [comment]
Might be worth clarifying the 7 means Couchbase Server version 7, if there are going to be multiple versions floating around

**Comment by markspolakovs** [comment]
> Might be worth clarifying the 7 means Couchbase Server version 7, if there are going to be multiple versions floating around

Well ideally there won't be :p good point though - I've got `couchbase-7` tags on all the CB7 ones, but ideally we'll rip out the CB6 ones before DP.

**Review by redm2 — APPROVED** [review]
Looks fine to me

**Comment by patrick-stephens** [comment]
> > Might be worth clarifying the 7 means Couchbase Server version 7, if there are going to be multiple versions floating around
> 
> Well ideally there won't be :p good point though - I've got `couchbase-7` tags on all the CB7 ones, but ideally we'll rip out the CB6 ones before DP.

Do we tag them in Grafana as well?

**Comment by markspolakovs** [comment]
> > > Might be worth clarifying the 7 means Couchbase Server version 7, if there are going to be multiple versions floating around
> > 
> > 
> > Well ideally there won't be :p good point though - I've got `couchbase-7` tags on all the CB7 ones, but ideally we'll rip out the CB6 ones before DP.
> 
> Do we tag them in Grafana as well?

Yeah, and we use those tags for interlinking. For example:

https://github.com/couchbaselabs/observability/blob/0360be4b3f37ac2144680f044436190b443f302f/microlith/grafana/provisioning/dashboards/node-overview-7.json#L551-L555

**Comment by patrick-stephens** [comment]
Looks like the inventory and node overview dashboards are a bit wonky: https://github.com/couchbaselabs/observability/actions/runs/1470944734

Is this just down to the metrics snapshot or something else?

**Comment by markspolakovs** [comment]
> Looks like the inventory and node overview dashboards are a bit wonky: [couchbaselabs/observability/actions/runs/1470944734](https://github.com/couchbaselabs/observability/actions/runs/1470944734)
> 
> Is this just down to the metrics snapshot or something else?

That'll be because we don't have the Cluster Monitor JSON. We may want to stub it out for the screenshots, but that's a CMOS for another day.

**Review by patrick-stephens — APPROVED** [review]

**Comment by patrick-stephens** [comment]
> > Looks like the inventory and node overview dashboards are a bit wonky: [couchbaselabs/observability/actions/runs/1470944734](https://github.com/couchbaselabs/observability/actions/runs/1470944734)
> > Is this just down to the metrics snapshot or something else?
> 
> That'll be because we don't have the Cluster Monitor JSON. We may want to stub it out for the screenshots, but that's a CMOS for another day.

Yeah probably something to do, be good to get valid screens in there but no rush now.

**Comment by markspolakovs** [comment]
Filed https://issues.couchbase.com/browse/CMOS-162 for the screenshots.

**Pull request merged**
