### PR TITLE
Updated Query Service Dashboard

### PR DESCRIPTION
**Pull request by bentonam**
- 39 New Panels
- Per Node Breakdowns
- Resource Breakdowns if Node and/or Process Exporter metrics are available
- Datasource as variable instead of hardcoded nam
query-service-dashboard
e

### CODE REVIEW

**Comment by markspolakovs** [comment]
Hey @bentonam, this looks really good, thanks for submitting it! A couple initial thoughts:

- It'd be good to eventually have the Prometheus be a variable on all dashboards, but IMHO in the short term it's better to stay consistent (read: hard-code it rather than having it be a variable on only one dashboard)
- In my head (and partly CMOS-17) the idea was for the query service dashboard to focus solely on query service performance, so I'm wondering if it's worth removing the node/process exporter stats (and in a perfect world we'd get the data we need out of ns_server anyway)

Having said that, this is an excellent dashboard and it'd be good to get it in.

**Comment by redm2** [comment]
These look incredible! A couple thoughts from my side:

There's a design decision to be made with repeating panels vs the current CMOS approach of a fixed/static number of graphs that update on (multi)variable selection, with any required overarching view factored out into its own dashboard.

For example, Single Cluster overview showing only a single cluster at once, with a separate "Couchbase Inventory" to show a summarised overview of all clusters. Versus repeating the cluster overview block panels per cluster selected.

There's pros/cons to each: repeating panels can get long very quickly, though they can be collapsed. And using variables to select which should be repeated helps this (though defaulting to _All_ could incur significant load time for a dashboard. Particularly for an Index overview, if there are thousands of GSI...).

-----

From testing locally using `make example-multi`, to make it work with CMOS' config:
- I hardcoded the Prometheus variable because of some Grafana provisioning issues (agree with Marks on long-term)
- `cluster_name` for every panel needed to be changed to `cluster`, due to naming differences in CMOS Prometheus
- Had to remove `$__rate_interval` from panels for their graphs to be rendered (some issue here, Query Inspector doesn't load so difficult to debug...)
- Node/exporter stats likely want to be factored out
- Remove default variable values (e.g., "Demo Cluster 1") because Grafana attempts to pre-populate these and could cause confusion upon first load.
- Remove `&autoFitPanels` secret header from links to stop Grafana from trying to fit the larger dashboard without scrolling 
- Standardise default refresh time to 15sec

I've got these changes in [another branch](https://github.com/couchbaselabs/observability/tree/gf-qry-srv-db-cmos-configuration-changes), and you can easily spin up example clusters to see what this looks like by running `make example-multi` with this checked out.

There's also Prom queries that return no data:
- `n1ql_avg_req_time`
- `n1ql_avg_svc_time`
- `n1ql_avg_response_size`
- `n1ql_avg_result_count`
- `n1ql_avg_response_size`

Which is something that needs to be looked into on our side (cc @markspolakovs as discussed).

**Comment by markspolakovs** [comment]
> There's also Prom queries that return no data:
> 
> * `n1ql_avg_req_time`
> * `n1ql_avg_svc_time`
> * `n1ql_avg_response_size`
> * `n1ql_avg_result_count`
> * `n1ql_avg_response_size`
> 
> Which is something that needs to be looked into on our side (cc @markspolakovs as discussed).

These looks like derived metrics (cf. https://github.com/couchbase/ns_server/blob/7ee50fad0e2ef2c23bc5c55a46b75d6b70806f0a/src/derived_metrics.erl?q=n1ql_avg_req_time#L22-L29) - I'm not sure how they're making it (or not) into the Prometheus, but worst comes to worst we can just derive them in PromQL.

**Comment by bentonam** [comment]
@markspolakovs  while the screenshot shows everything expanded, typically for "Node Resources" and the per node repeatable panels I leave collapsed by default.  This way less queries are ran on dashboard load, but also do not cause too much confusion unless you want to drill down to that set of dashboards. 

query-service-dashboard-collapsed

For the datasource as a variable, having gone down the route of not making it a variable initially, and making it one after the fact is a huge pain to go and change.  This is why I made it with it as a variable, and it requires no additional configuration, it will just load whatever prometheus datasources are available.  

Another change that I made was the query dashboard was populating the `cluster` variable, I changed that to `cluster_name` for consistency.  But the query to populate the variable was `label_values(multimanager_cluster_checker_status,cluster_name)` which assumes that `multimanager_cluster_checker_status` exists.  I changed this to be service specific `label_values(n1ql_requests,cluster_name)` this way if someone is loading the dashboard without multimanager it will still work as intended. 

For the system metrics, there are some of the values exposed from couchbase metrics.  

```
sysproc_page_faults_raw{proc="cbq-engine",category="system-processes"} 392890
sysproc_minor_faults_raw{proc="cbq-engine",category="system-processes"} 392890
sysproc_mem_size{proc="cbq-engine",category="system-processes"} 4874149888
sysproc_mem_share{proc="cbq-engine",category="system-processes"} 67985408
sysproc_mem_resident{proc="cbq-engine",category="system-processes"} 1310863360
sysproc_major_faults_raw{proc="cbq-engine",category="system-processes"} 0
sysproc_cpu_utilization{proc="cbq-engine",category="system-processes"} 185
```

for those that overlap with node / process exporter, I can change the PromQL statement to be an `or` so use process exporter if that metrics exist otherwise fall back to `sysproc_`.  But I'm not 100% certain of the value accuracy as `sysproc` says `cbq-engine` is 185% from the couchbase metrics and process exporter says 98.2%.  

I'm happy to change whatever you'd like just let me know.  I personally just like to see CPU/Mem/Disk/Network on the same dashboard so I can quickly reference if needed.

**Comment by bentonam** [comment]
I am going to close this PR, and open a new one with separate dashboards as to not conflict with any of the current dashboards.

**Pull request closed without merging**
