### PR TITLE
Update services, dashboards

### PR DESCRIPTION
**Pull request by redm2**

### CODE REVIEW

**Comment by markspolakovs** [comment]
Single Cluster Overview:

Having zero indexes shouldn't be red, there are valid reasons for not using GSI
image

I really like the gradient effect you have on the graphs, but for some it can make it a bit too crowded - example:
image


Data Service Overview: 

Doesn't scale great when you have lots of buckets (remember that CBS can support up to 30)
image


Query Service Overview:

Is this number a total, or current? If current, over what time period? (Could possibly do with adding that to the panel description.)
image


Apart from those, looks good!

**Comment by redm2** [comment]
> I really like the gradient effect you have on the graphs, but for some it can make it a bit too crowded

I agree. For some reason the opacity was at 100 so I have reduced it to 40 (same as all others), which should improve things.

> Data Service Overview: Doesn't scale great when you have lots of buckets (remember that CBS can support up to 30)

Definitely, this is a design decision that needs to be made. 
- Either we could have the query return `topk`, in which case it's not a great Data Service overview because we're not showing all buckets. Or we could repeat the panel for each instance of the variable, which could make it difficult to scroll.
- Preferably we'd be able to show top K at a glance and be able to view all by full-sizing the panel, but as far as I know this is only possible with tables, which don't look quite as nice.

Will push the fixes for the rest.

**Comment by markspolakovs** [comment]
Cluster Overview:

NITPICKING: if there's missing data, this table seems to have a white background:
image

Node Overview:

This needs updating for the new values (on all the dashboards)
image

Apart from that, LGTM

**Comment by redm2** [comment]
>  if there's missing data, this table seems to have a white background:

That's actually by design - it's meant to be a very obvious indicator of something going wrong. But I didn't take into account the fact that that table uses info from both JSON API and Prometheus, and so that happens when Prometheus is being slow on initialisation (since the API updates much more quickly).

**Review by markspolakovs — APPROVED** [review]
ship it

**Pull request merged**
